on:
  push:
    branches-ignore:
      - 'none'

name: Check WASM compatability

jobs:
  build:
    name: Build WASM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.4.0
      - run: cd ./wasm && wasm-pack build --target web
